 -- MySQL Script generated by MySQL Workbench
-- pirmdiena, 2021. gada  5. jūlijs, 10:43:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artists` (
  `name` VARCHAR(45) NOT NULL,
  `artistId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`artistId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Albums` (
  `albumId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `artists_artistId` INT NOT NULL,
  PRIMARY KEY (`albumId`, `artists_artistId`),
  INDEX `fk_Albums_artists1_idx` (`artists_artistId` ASC) VISIBLE,
  CONSTRAINT `fk_Albums_artists1`
    FOREIGN KEY (`artists_artistId`)
    REFERENCES `mydb`.`artists` (`artistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media_types` (
  `mediaTypeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mediaTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `genreID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tracks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tracks` (
  `trackId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `composer` VARCHAR(45) NOT NULL,
  `milliSecounds` INT NOT NULL,
  `bytes` INT NOT NULL,
  `unitPrice` INT NOT NULL,
  `Albums_albumId` INT NOT NULL,
  `Albums_artists_artistId` INT NOT NULL,
  `genres_genreID` INT NOT NULL,
  `media_types_mediaTypeId` INT NOT NULL,
  PRIMARY KEY (`trackId`, `Albums_albumId`, `Albums_artists_artistId`, `genres_genreID`, `media_types_mediaTypeId`),
  INDEX `fk_tracks_Albums1_idx` (`Albums_albumId` ASC, `Albums_artists_artistId` ASC) VISIBLE,
  INDEX `fk_tracks_genres1_idx` (`genres_genreID` ASC) VISIBLE,
  INDEX `fk_tracks_media_types1_idx` (`media_types_mediaTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_tracks_Albums1`
    FOREIGN KEY (`Albums_albumId` , `Albums_artists_artistId`)
    REFERENCES `mydb`.`Albums` (`albumId` , `artists_artistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracks_genres1`
    FOREIGN KEY (`genres_genreID`)
    REFERENCES `mydb`.`genres` (`genreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracks_media_types1`
    FOREIGN KEY (`media_types_mediaTypeId`)
    REFERENCES `mydb`.`media_types` (`mediaTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `playlistId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`playlistId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlistTrack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlistTrack` (
  `trackId` INT NOT NULL,
  `playlist_playlistId` INT NOT NULL,
  `tracks_trackId` INT NOT NULL,
  `tracks_Albums_albumId` INT NOT NULL,
  `tracks_Albums_artists_artistId` INT NOT NULL,
  `tracks_genres_genreID` INT NOT NULL,
  `tracks_media_types_mediaTypeId` INT NOT NULL,
  PRIMARY KEY (`trackId`, `playlist_playlistId`, `tracks_trackId`, `tracks_Albums_albumId`, `tracks_Albums_artists_artistId`, `tracks_genres_genreID`, `tracks_media_types_mediaTypeId`),
  INDEX `fk_playlistTrack_playlist1_idx` (`playlist_playlistId` ASC) VISIBLE,
  INDEX `fk_playlistTrack_tracks1_idx` (`tracks_trackId` ASC, `tracks_Albums_albumId` ASC, `tracks_Albums_artists_artistId` ASC, `tracks_genres_genreID` ASC, `tracks_media_types_mediaTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_playlistTrack_playlist1`
    FOREIGN KEY (`playlist_playlistId`)
    REFERENCES `mydb`.`playlist` (`playlistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlistTrack_tracks1`
    FOREIGN KEY (`tracks_trackId` , `tracks_Albums_albumId` , `tracks_Albums_artists_artistId` , `tracks_genres_genreID` , `tracks_media_types_mediaTypeId`)
    REFERENCES `mydb`.`tracks` (`trackId` , `Albums_albumId` , `Albums_artists_artistId` , `genres_genreID` , `media_types_mediaTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `employeesId` INT NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `reportsTo` INT NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `hireDate` DATETIME NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `employees_employeesId` INT NOT NULL,
  PRIMARY KEY (`employeesId`, `employees_employeesId`),
  INDEX `fk_employees_employees1_idx` (`employees_employeesId` ASC) VISIBLE,
  CONSTRAINT `fk_employees_employees1`
    FOREIGN KEY (`employees_employeesId`)
    REFERENCES `mydb`.`employees` (`employeesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customerId` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `employees_employeesId` INT NOT NULL,
  `employees_employees_employeesId` INT NOT NULL,
  PRIMARY KEY (`customerId`, `employees_employeesId`, `employees_employees_employeesId`),
  INDEX `fk_customers_employees1_idx` (`employees_employeesId` ASC, `employees_employees_employeesId` ASC) VISIBLE,
  CONSTRAINT `fk_customers_employees1`
    FOREIGN KEY (`employees_employeesId` , `employees_employees_employeesId`)
    REFERENCES `mydb`.`employees` (`employeesId` , `employees_employeesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoices` (
  `invoicesId` INT NOT NULL,
  `customerId` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `billingAdress` VARCHAR(45) NOT NULL,
  `billingCity` VARCHAR(45) NOT NULL,
  `billingState` VARCHAR(45) CHARACTER SET 'armscii8' NOT NULL,
  `billingCountry` VARCHAR(45) COLLATE 'Default Collation' NOT NULL,
  `billingPostalCode` VARCHAR(45) NOT NULL,
  `total` INT NOT NULL,
  `customers_customerId` INT NOT NULL,
  PRIMARY KEY (`invoicesId`, `customers_customerId`),
  INDEX `fk_invoices_customers1_idx` (`customers_customerId` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_customers1`
    FOREIGN KEY (`customers_customerId`)
    REFERENCES `mydb`.`customers` (`customerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoicesItesms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoicesItesms` (
  `invocesItemId` INT NOT NULL,
  `unitPrice` INT NOT NULL,
  `quantity` INT NOT NULL,
  `tracks_trackId` INT NOT NULL,
  `tracks_Albums_albumId` INT NOT NULL,
  `tracks_Albums_artists_artistId` INT NOT NULL,
  `tracks_genres_genreID` INT NOT NULL,
  `tracks_media_types_mediaTypeId` INT NOT NULL,
  `invoices_invoicesId` INT NOT NULL,
  PRIMARY KEY (`invocesItemId`, `tracks_trackId`, `tracks_Albums_albumId`, `tracks_Albums_artists_artistId`, `tracks_genres_genreID`, `tracks_media_types_mediaTypeId`, `invoices_invoicesId`),
  INDEX `fk_invoicesItesms_tracks1_idx` (`tracks_trackId` ASC, `tracks_Albums_albumId` ASC, `tracks_Albums_artists_artistId` ASC, `tracks_genres_genreID` ASC, `tracks_media_types_mediaTypeId` ASC) VISIBLE,
  INDEX `fk_invoicesItesms_invoices1_idx` (`invoices_invoicesId` ASC) VISIBLE,
  CONSTRAINT `fk_invoicesItesms_tracks1`
    FOREIGN KEY (`tracks_trackId` , `tracks_Albums_albumId` , `tracks_Albums_artists_artistId` , `tracks_genres_genreID` , `tracks_media_types_mediaTypeId`)
    REFERENCES `mydb`.`tracks` (`trackId` , `Albums_albumId` , `Albums_artists_artistId` , `genres_genreID` , `media_types_mediaTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoicesItesms_invoices1`
    FOREIGN KEY (`invoices_invoicesId`)
    REFERENCES `mydb`.`invoices` (`invoicesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
